'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const E=require('../src/engine.js'),W=require('../src/world.js'),D=require('../src/data.js');
const fresh=()=>E.newGame('survivor',42);
function action(s,type,id){const r=E.action(s,type,id);assert.ok(r.ok,r.message);E.validate(s);return r;}
test('version-2 saves migrate additively without rerolling or losing progress',()=>{const old=fresh();old.day=12;old.time=900;delete old.world;for(const c of Object.values(old.camps))for(const k of ['condition','braced','wildlife','fishStock'])delete c[k];const result=E.validate(old);assert.equal(result.day,12);assert.equal(result.time,900);assert.equal(result.seed,old.seed);assert.deepEqual(result.inv,old.inv);assert.equal(result.camps.river.condition,100);assert.deepEqual(result.world.hazards,[]);assert.equal(old.world,undefined);});
test('discovery precedes claim; all landmarks pay exactly once including overflow',()=>{for(const id of Object.keys(D.landmarks)){const s=fresh();s.location=id;const before=JSON.stringify(s);assert.equal(E.action(s,'investigate',id).ok,false);assert.equal(JSON.stringify(s),before);action(s,'explore');assert.ok(s.world.discovered.includes(id));s.event=null;s.energy=100;s.time=600;s.inv={stone:48};for(const [k,n] of Object.entries(D.landmarks[id].mats))s.inv[k]=n;const reward=Object.keys(D.landmarks[id].reward)[0];action(s,'investigate',id);assert.equal(s.inv[reward],undefined);assert.equal(s.camps[id].cache[reward],1);const claimed=JSON.stringify(s);assert.equal(E.action(s,'investigate',id).ok,false);assert.equal(JSON.stringify(s),claimed);}});
test('cave and waterfall require preparation, and flood blocks waterfall claim',()=>{const s=fresh();s.location='rocks';s.world.discovered=['rocks','river'];assert.match(E.available(s,'investigate','rocks'),/คบไฟ/);s.inv.torch=1;action(s,'investigate','rocks');assert.equal(s.inv.torch,undefined);s.location='river';s.inv.climbing_rope=1;s.day=4;s.world.hazards=W.hazardsFor(s,'storm',4);assert.match(E.available(s,'investigate','river'),/น้ำตก/);});
test('water filter, compass, boots and binoculars have functional benefits',()=>{const s=fresh();const travel=E.cost(s,'travel');s.inv.compass=1;s.inv.boots=1;assert.deepEqual(E.cost(s,'travel'),[travel[0]-15,travel[1]-4]);const chance=W.huntChance(s);s.inv.binoculars=1;assert.ok(Math.abs(W.huntChance(s)-chance-.1)<.0001);s.inv.water_filter=1;s.inv.dirty=3;action(s,'filter');assert.equal(s.inv.dirty,1);assert.equal(s.inv.water,5);assert.equal(s.camps.clearing.fire,0);});
test('warning forecasts match next morning and generated closures keep every site reachable',()=>{for(let day=3;day<30;day++){const s=fresh();s.day=day;s.time=1200;s.forecast=day%3===0?'rain':'storm';const expected=W.hazardsFor(s,s.forecast,day+1);action(s,'sleep');assert.deepEqual(W.active(s),expected);const seen=new Set(['clearing']),todo=['clearing'];while(todo.length){const id=todo.shift();for(const next of D.sites.find(a=>a.id===id).links)if(!seen.has(next)&&!W.blocked(s,id,next)){seen.add(next);todo.push(next);}}assert.equal(seen.size,7);}});
test('consecutive storms do not cut off the alternate route',()=>{const s=fresh();for(let day=4;day<=30;day++){s.day=day;s.weather='storm';W.dawn(s,()=>{});assert.ok(!(W.blocked(s,'river','rocks')&&W.blocked(s,'forest','ruins')));}});
test('flood changes travel, fishing and water yields; clears on expiry',()=>{const s=fresh();s.day=4;s.location='river';s.world.hazards=W.hazardsFor(s,'storm',4);s.inv.rod=1;s.tools.rod=20;const before=JSON.stringify(s);assert.equal(E.action(s,'travel','rocks').ok,false);assert.equal(E.action(s,'fish').ok,false);assert.equal(JSON.stringify(s),before);action(s,'water');assert.equal(s.inv.dirty,1);s.day=5;assert.equal(W.blocked(s,'river','rocks'),undefined);});
test('fallen trees can be cleared from either endpoint, using one axe charge',()=>{for(const id of ['forest','ruins']){const s=fresh();s.day=5;s.location=id;s.weather='storm';s.world.hazards=W.hazardsFor(s,'storm',5);assert.match(E.available(s,'clearTrail'),/ขวาน/);s.inv.axe=1;s.tools.axe=2;action(s,'clearTrail');assert.equal(s.tools.axe,1);assert.equal(W.blocked(s,'forest','ruins'),undefined);}});
test('storm damage applies to remote camps, bracing and tarp reduce it; repair restores shelter',()=>{const s=fresh();s.day=5;s.weather='storm';s.time=1200;for(const id of ['clearing','forest'])s.camps[id].structures=['shelter'];s.camps.clearing.condition=45;s.inv.storm_tarp=1;s.camps.clearing.braced=true;action(s,'sleep');assert.equal(s.camps.clearing.condition,43);assert.equal(s.camps.forest.condition,82);assert.equal(s.camps.clearing.braced,false);s.camps.clearing.condition=30;assert.equal(W.shelter(s),false);s.inv.wood=3;s.inv.fiber=2;action(s,'repair');assert.equal(s.camps.clearing.condition,75);assert.equal(W.shelter(s),true);});
test('hunting depletes wildlife, migration restores it faster, fish stocks recover',()=>{const s=fresh();s.day=4;s.inv.spear=1;s.tools.spear=18;const chance=W.huntChance(s);action(s,'hunt');assert.equal(s.camps.clearing.wildlife,4);assert.ok(W.huntChance(s)<chance);s.event=null;s.camps.clearing.wildlife=0;assert.match(E.available(s,'hunt'),/รอยสัตว์/);const dest=W.migration(s,s.day+1);s.camps[dest].wildlife=0;W.night(s,()=>{});assert.equal(s.camps[dest].wildlife,2);});
test('corrupt world extensions are rejected',()=>{for(const mutate of [s=>s.world.claimed=['river'],s=>s.world.discovered=['missing'],s=>s.camps.river.condition=-1,s=>s.camps.forest.wildlife=100,s=>s.world.hazards=[{type:'flood',site:'river',edge:['river','valley'],until:4}]]){const s=fresh();mutate(s);assert.throws(()=>E.validate(s));}});
