'use strict';
(()=>{
const $=id=>document.getElementById(id),E=Survival,D=WILD,SAVE='wildland_autosave_v2',CHECKPOINT='wildland_checkpoint_v2';
const paths={mountain:'M2 20 9 6l4 7 3-5 6 12H2ZM6 12l3 2 3-2M15 11l3 3',compass:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM16 8l-3 5-5 3 3-5 5-3Z',leaf:'M20 3C9 1 2 7 5 15c7 7 17 0 15-12ZM4 21 15 9',pack:'M7 7V5a5 5 0 0 1 10 0v2M6 7h12a2 2 0 0 1 2 2v11H4V9a2 2 0 0 1 2-2ZM8 13h8v5H8ZM10 7v3m4-3v3',book:'M3 3h7l2 2 2-2h7v16h-7l-2 2-2-2H3V3ZM12 5v16M6 7h3m6 0h3M6 11h3m6 0h3',tool:'M14 3a6 6 0 0 0-7 8l-5 6a3 3 0 0 0 4 4l6-6a6 6 0 0 0 8-7l-4 4-4-4 4-4Z',axe:'M5 21 15 4M10 4l6-2 5 6-4 5-7-9ZM9 14l3 2',spear:'M3 21 16 8M14 4l7-3-3 7-4-4Z',fish:'M3 12c5-9 12-9 16 0-4 9-11 9-16 0ZM19 12l4-4v8l-4-4ZM8 10h.01',wood:'M4 8 16 3c5-1 8 7 4 10L8 20M4 8c5-2 10 8 4 12-5 2-10-8-4-12ZM4 12c2-1 5 3 3 4M10 8l5-2m-2 7 5-2',rock:'M3 16 6 7l9-4 6 9-3 8H8l-5-4ZM6 7l7 5 8 0M13 12l-5 8',food:'M7 3v6m-3-6v6a3 3 0 0 0 6 0V3M7 12v9M18 21V3c-5 3-5 10 0 10',water:'M12 2S4 11 4 15a8 8 0 0 0 16 0c0-4-8-13-8-13ZM8 15a4 4 0 0 0 4 4',heart:'M20 4c-3-2-6 0-8 2-2-2-5-4-8-2-5 4-1 9 8 16 9-7 13-12 8-16Z',energy:'M13 2 4 14h7l-1 8 10-13h-7l0-7Z',temp:'M9 14V5a3 3 0 0 1 6 0v9a5 5 0 1 1-6 0ZM12 9v9m0 0h.01',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',cloud:'M6 18a5 5 0 0 1-1-10A7 7 0 0 1 18 7a5 5 0 0 1 0 11H6Z',rain:'M5 14a4 4 0 0 1 0-8A6 6 0 0 1 17 6a4 4 0 0 1 2 8M7 17l-2 4m8-4-2 4m8-4-2 4',storm:'M5 14a4 4 0 0 1 0-8A6 6 0 0 1 17 6a4 4 0 0 1 2 8M12 12l-4 6h5l-2 5 6-8h-5',clock:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM12 6v6l4 2',calendar:'M4 5h16v16H4V5ZM7 2v6m10-6v6M4 10h16M8 14h2m4 0h2M8 17h2',tent:'M2 20 12 3l10 17H2ZM8 20l4-9 4 9M12 3V1',fire:'M13 2c3 7-4 6-2 11 2 1 4-1 4-4 8 7 4 13-3 13-9 0-12-9-5-15-1 5 3 5 3 2l3-7Z',sleep:'M20 15a9 9 0 0 1-11-12 9 9 0 1 0 11 12ZM17 2v5m-2-3h5',shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6l-9-4ZM8 12l3 3 5-6',medical:'M8 3h8v5h5v8h-5v5H8v-5H3V8h5V3Z',radio:'M3 8h18v13H3V8ZM5 8 18 2M7 12h5v5H7ZM16 13h2m-2 4h2',signal:'M12 13v9M9 10a4 4 0 0 1 6 0M5 7a9 9 0 0 1 14 0M2 4a13 13 0 0 1 20 0',battery:'M2 7h18v12H2V7ZM20 11h2v4h-2M5 10v6m4-6v6m4-6v6',pin:'M12 22S4 13 4 9a8 8 0 0 1 16 0c0 4-8 13-8 13ZM12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',help:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM9 8a3 3 0 1 1 5 2l-2 2v2m0 3h.01',check:'M5 12l4 4L20 5',close:'M6 6l12 12M6 18 18 6',sound:'M3 9h4l5-5v16l-5-5H3V9ZM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',muted:'M3 9h4l5-5v16l-5-5H3V9ZM16 9l6 6m0-6-6 6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM9 2h6l1 4 4 1 2 5-3 3-1 5-5 2-3-3-5-1-2-5 3-3 1-5 2-3Z',arrow:'M4 12h16m-6-6 6 6-6 6',save:'M3 3h15l3 3v15H3V3ZM7 3v6h9V3M7 21v-7h10v7',eye:'M2 12s4-8 10-8 10 8 10 8-4 8-10 8S2 12 2 12ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6'};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.compass}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const time=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const duration=n=>n>=60?`${Math.floor(n/60)} ชม.${n%60?` ${n%60} น.`:''}`:`${n} น.`;
let G,tab='gather',craftFilter='camp',invFilter='all',mapSelected='clearing',toastTimer,modalMode='',sceneReady=false,saveError='',storageWorks=true;
try{const raw=localStorage.getItem(SAVE);G=raw?E.validate(JSON.parse(raw)):E.newGame();}catch(err){G=E.newGame();saveError='อ่านเซฟเดิมไม่ได้ จึงเปิดการเดินทางใหม่ • ไฟล์เซฟเดิมยังไม่ถูกลบ';}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(G));storageWorks=true;$('saveIndicator').innerHTML='<i></i> บันทึกแล้ว';}catch(e){storageWorks=false;$('saveIndicator').textContent='บันทึกไม่ได้ • ส่งออกเซฟ';}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200);}
function openModal(title,body,mode='normal',eyebrow='FIELD NOTES'){modalMode=mode;$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalEyebrow').textContent=eyebrow;$('closeModal').hidden=mode==='event';if(!$('modal').open)$('modal').showModal();}
function closeModal(){if(modalMode==='event')return;$('modal').close();modalMode='';}
function run(type,id,quantity=1){
const previousRaw=E.count(G,'raw');
const result=E.action(G,type,id,quantity);
if(!result.ok){actionAudio.play('error');toast(result.message);return;}
actionAudio.play(({investigate:'explore',repair:'craft',reinforce:'craft',clearTrail:'wood',filter:'water'})[type]||type,{camp:D.recipes[id]?.group==='camp',medical:D.recipes[id]?.group==='medical',itemType:D.items[id]?.type,gained:E.count(G,'raw')>previousRaw});
if(G.ended)actionAudio.play(G.won?'win':'lose');else if(G.event)actionAudio.play('encounter');
save();render();toast(result.message);if(G.event)showEvent();else if(G.ended)showEnd();
}
const tabs=[['gather','compass','ลงมือ','วันนี้จะทำอะไร?'],['craft','tool','สร้าง','สร้างแคมป์ เครื่องมือ และทำอาหาร'],['inventory','pack','กระเป๋า','สัมภาระและคลังของพื้นที่'],['map','mountain','แผนที่','วางแผนเส้นทางและเดินทาง'],['quest','signal','ภารกิจ','เป้าหมาย ชิ้นส่วนวิทยุ และจุดสำรวจ'],['journal','book','บันทึก','บันทึกการเดินทาง']];
function setTab(next,{focus=false}={}){const changed=tab!==next;tab=next;renderTabs();renderActivity();if(changed){const top=$('activityTitle').getBoundingClientRect().top-$('mainNav').getBoundingClientRect().bottom;if(top<0||top>innerHeight*.6)$('activityTitle').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}if(focus)$('activityContent').focus({preventScroll:true});}
function navBadges(){
  const craftable=Object.entries(D.recipes).filter(([k,r])=>!E.available(G,'craft',k)&&!(r.group==='camp'&&E.camp(G).structures.includes(k))).length,hazards=WorldRules.active(G).length,parts=['radio','battery','wire'].filter(k=>E.count(G,k)).length,weight=E.weight(G)/E.capacity(G);
  return {craft:G.difficulty!=='wild'&&craftable?[craftable,'ok',`สร้างได้ ${craftable} อย่าง`]:null,map:hazards?['!','warn',`เส้นทางถูกปิด ${hazards} จุด`]:null,inventory:weight>1?['!','warn','สัมภาระหนักเกิน']:null,quest:G.difficulty!=='wild'&&!E.available(G,'signal')?['!','ok','ส่งสัญญาณได้แล้ว']:parts?[`${parts}/3`,'',`ชิ้นส่วนวิทยุ ${parts}/3`]:null};
}
function renderTabs(){const badges=navBadges();$('mainNav').innerHTML=tabs.map(([k,i,t],j)=>{const b=badges[k];return `<button data-tab="${k}" class="${tab===k?'active':''}" aria-current="${tab===k?'page':'false'}" title="${t} (${j+1})${b?` • ${b[2]}`:''}">${icon(i)}<span class="nav-label">${t}</span>${b?`<span class="nav-badge ${b[1]}" aria-label="${esc(b[2])}">${b[0]}</span>`:''}</button>`;}).join('');}
// The single most useful thing to do next, with a one-click jump to where it happens.
function nextStep(){
  const step=SurvivalAdvice.next(G);if(!step)return null;
  const attrs=step.newGame?'data-newgame':step.sleep?'data-open-sleep':[['nav',step.nav],['navfilter',step.filter],['navmap',step.map],['navaction',step.action],['navactionid',step.actionId],['navitem',step.item]].filter(([,v])=>v).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ');
  return {...step,go:attrs};
}
function render(){
const sd=E.site(G),c=E.camp(G),w=D.weather[G.weather];
$('topMeta').innerHTML=`<div class="hud-item">${icon('calendar')}<strong>วันที่ ${G.day}<small>/30</small></strong></div><div class="hud-item">${icon(G.time>=1140?'sleep':'clock')}<strong>${time(G.time)}</strong><small class="hud-extra">เหลือ ${duration(1320-G.time)}</small></div><div class="hud-item weather-meta" title="พรุ่งนี้: ${D.weather[G.forecast].name}">${icon(w.icon)}<strong>${E.temperature(G)}°</strong><small class="hud-extra">${w.name}</small></div>`;
$('difficultyLabel').textContent=D.difficulties[G.difficulty].name;
const steps=[['เพิงพัก',Boolean(G.milestones.shelter)],['หลุมไฟ',Boolean(G.milestones.firepit)],['แหล่งน้ำ',G.visited.includes('river')||G.visited.includes('valley')]],step=nextStep();
$('objective').hidden=!step;
$('objective').innerHTML=step?`<div class="objective ${step.tone||''}"><div class="objective-icon">${icon(step.icon)}</div><div class="objective-text"><small>${step.critical?'':'ขั้นต่อไป • '}${esc(step.kicker)}</small><strong>${esc(step.title)}</strong><span>${esc(step.detail)}</span></div>${G.ended||G.difficulty==='wild'||step.critical||steps.every(x=>x[1])?'':`<div class="objective-steps" aria-label="ภารกิจแรก ${steps.filter(x=>x[1]).length} จาก 3">${steps.map(([n,x])=>`<i class="step-dot ${x?'done':''}" title="${n}${x?' ✓':''}"></i>`).join('')}</div>`}<button class="button primary objective-go" ${step.go}>${esc(step.label)}${icon('arrow')}</button></div>`:'';
$('biomeLabel').innerHTML=icon('pin')+sd.subtitle;$('sceneCoord').textContent=`ALT ${sd.alt.toLocaleString()} M`;$('locationIndex').textContent=`พื้นที่ ${D.sites.indexOf(sd)+1}/7 • คุณอยู่ที่`;$('locationName').textContent=sd.name;$('locationDescription').textContent=sd.desc;
$('sceneWeather').innerHTML=`${icon(w.icon)}<strong>${E.temperature(G)}°</strong><span>${w.name}</span><span class="forecast">พรุ่งนี้ ${D.weather[G.forecast].name}</span>`;
const stats=[['health','heart','สุขภาพ','#c2ccab'],['energy','energy','พลังงาน','#d0bb7e'],['food','food','ความอิ่ม','#c79a79'],['water','water','น้ำในร่างกาย','#87b0b9'],['warmth','temp','ความอบอุ่น','#bbab84']];
$('vitals').innerHTML=stats.map(([k,i,n,color])=>`<div class="vital ${G[k]<25?'critical':''}" style="--stat:${G[k]<25?'#dd8b75':color}"><div class="vital-head"><span class="vital-name">${icon(i)}${n}</span><span class="vital-value">${Math.round(G[k])}<small> / 100</small></span></div><div class="meter" role="meter" aria-label="${n}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(G[k])}"><i style="width:${G[k]}%"></i></div></div>`).join('');
$('miniVitals').innerHTML=stats.map(([k,i,n,color])=>`<div class="mini-vital ${G[k]<25?'critical':''}" style="--stat:${G[k]<25?'#dd8b75':color}" title="${n} ${Math.round(G[k])}/100">${icon(i)}<span class="sr-only">${n}</span><b>${Math.round(G[k])}</b><i style="--v:${G[k]}%"></i></div>`).join('');
$('conditionLabel').textContent=G.health<30?'วิกฤต':G.sickness||G.wound?'ต้องดูแล':'สถานะปกติ';
const conditions=[];if(G.sickness)conditions.push(['medical',`ป่วย ${G.sickness} คืน`,true]);if(G.wound)conditions.push(['medical',`บาดเจ็บ ${G.wound} คืน`,true]);if(G.wet>25)conditions.push(['rain',`เปียก ${Math.round(G.wet)}%`,true]);if(G.warmth<25)conditions.push(['temp','หนาวจัด',true]);if(c.fire>0)conditions.push(['fire',`ไฟ ${duration(c.fire)}`,false]);if(!conditions.length)conditions.push(['check','ไม่มีอาการผิดปกติ',false]);
$('conditions').innerHTML=conditions.map(([i,n,b])=>`<span class="condition ${b?'warning':''}">${icon(i)}${n}</span>`).join('');
const sleepReason=E.available(G,'sleep');$('sleepButton').innerHTML=icon('sleep')+(G.time<900?'นอนพักได้ตั้งแต่ 15:00':'นอนพัก → เช้าวันถัดไป');$('sleepButton').disabled=Boolean(sleepReason);$('sleepButton').title=sleepReason||'ดูสรุปก่อนเข้านอน';$('campSite').textContent=sd.name;

$('campOverview').innerHTML=(c.structures.length?c.structures.map(k=>`<div class="camp-item"><div class="camp-icon">${icon(D.recipes[k].icon)}</div><div><strong>${D.recipes[k].name}</strong><small>${k==='firepit'?(c.fire>0?`ไฟเหลือ ${duration(c.fire)}`:'ยังไม่ได้จุดไฟ'):k==='shelter'?(WorldRules.shelter(G)?'ป้องกันฝน • พร้อมพักผ่อน':'ชำรุด • ต้องซ่อมก่อนพัก'):'พร้อมใช้งาน'}</small></div><i class="status-dot" style="${k==='firepit'&&!c.fire?'background:#71775f':''}"></i></div>`).join(''):`<div class="camp-empty">${icon('tent')}<div>ยังไม่มีที่พักในพื้นที่นี้<br>เริ่มจากเพิงพัก เพื่อผ่านคืนแรก</div></div>`)+`<button class="camp-link" data-nav="craft">จัดการแคมป์ <span>↗</span></button>`;
if(c.structures.length)$('campOverview').insertAdjacentHTML('afterbegin',`<div class="camp-health-label"><span>ความแข็งแรง ${c.condition}%</span><span>${c.braced?'ค้ำยันแล้ว':c.condition<40?'ต้องซ่อม':'พร้อมใช้งาน'}</span></div>`);
$('recentLogs').innerHTML=G.logs.slice(0,3).map(logHTML).join('');$('timeRemaining').textContent=`${time(G.time)} • เหลือเวลาวันนี้ ${duration(1320-G.time)}`;renderTabs();renderActivity();if(sceneReady)Landscape.update(G);natureAudio.update(G.weather);
}
function logHTML(l){return `<div class="log-entry ${esc(l.tone)}"><small>DAY ${String(l.day).padStart(2,'0')} / ${time(l.time)}</small>${esc(l.text)}</div>`;}
const actions=[['forage','leaf','หาอาหาร','ผลไม้ 2–3 • มีโอกาสพบสมุนไพร'],['wood','wood','เก็บไม้ฟืน','ไม้ตามพื้นที่ • ขวานช่วยเพิ่มผลผลิต'],['fiber','leaf','เก็บเส้นใย','วัสดุสำหรับเพิงพัก เชือก และยา'],['stone','rock','เก็บก้อนหิน','ใช้สร้างหลุมไฟและเครื่องมือ'],['water','water','เก็บน้ำ','น้ำจากลำธาร 3 หน่วย • ต้องต้ม'],['explore','compass','สำรวจเส้นทาง','หาวัสดุ ชิ้นส่วนกู้ภัย • เสี่ยงบาดเจ็บ'],['hunt','spear','ล่าสัตว์','เนื้อ 2–4 • สำเร็จ 65% (ป่าดิบ 80%)'],['fish','fish','ตกปลา','เนื้อปลา 1–3 • ต้องอยู่ใกล้น้ำ'],['rest','sleep','พักสั้น','พลังงาน +21 • ใต้เพิงพัก +27']];
const actionGroups=[['materials','wood','เก็บวัสดุ','ใช้สร้างแคมป์และเครื่องมือ',['wood','fiber','stone']],['supplies','water','อาหารและน้ำ','น้ำจากลำธารต้องต้มก่อนดื่ม',['water','forage','hunt','fish']],['explore','compass','สำรวจและพักผ่อน','เวลาเดินเฉพาะเมื่อคุณลงมือ',['explore','rest']]];
function actionCard(a){const [k,i,n,d]=a,reason=E.available(G,k),[mins,energy]=E.cost(G,k);return `<button class="action-card" data-action="${k}" ${reason?'disabled':''} title="${esc(reason||d)}"><span class="card-top">${icon(i,'card-icon')}<span class="card-arrow" aria-hidden="true">${reason?'':'→'}</span></span><span class="action-title">${n}</span><span class="action-desc">${d}</span><span class="card-cost">${reason?`<span class="locked">${esc(reason)}</span>`:`<span>${icon('clock')}${duration(mins)}</span><span>${icon('energy')}${energy?`−${energy}`:'+21~27'}</span>`}</span></button>`;}
function journeyGoalsHTML(){
  return `<section class="journey-goals"><div class="panel-title"><h2>${icon('check')} เป้าหมายระหว่างทาง</h2><span class="micro">${Object.keys(G.milestones.goals||{}).length}/${E.goals.length} สำเร็จ</span></div>${E.goals.map(goal=>{const done=Boolean(G.milestones.goals?.[goal.id]),raw=goal.progress(G),ratio=typeof raw==='number'?raw:(raw?1:0);return `<article class="journey-goal ${done?'done':''}"><div class="journey-goal-head"><strong>${done?icon('check'):icon('compass')}${goal.title}</strong><span>${esc(goal.label(G))}</span></div><p>${goal.description}</p><div class="meter"><i style="width:${Math.round(Math.max(0,Math.min(1,ratio))*100)}%"></i></div><small>รางวัล: ${Object.entries(goal.reward).map(([id,n])=>`${D.items[id].name} ×${n}`).join(' / ')}</small></article>`;}).join('')}</section>`;
}
function enhanceMapPlanning(){
  const wrap=$('activityContent').querySelector('.map-wrap'),detail=$('activityContent').querySelector('.map-details');if(!wrap||!detail)return;
  const plan=E.routePlan(G,mapSelected),selected=D.sites.find(x=>x.id===mapSelected),body=detail.querySelector('div');
  const risk=plan.reachable?`${Math.round(plan.risk*100)}%`:'—';
  const path=plan.reachable?plan.path.map(id=>D.sites.find(x=>x.id===id).name).join(' → '):'ไม่มีเส้นทางที่เปิดอยู่ในขณะนี้';
   body.insertAdjacentHTML('beforeend',`<div class="route-summary ${plan.reachable?'':'blocked'}"><strong>${icon(plan.reachable?'compass':'storm')} แผนการเดินทาง</strong><span>${esc(path)}</span><small>${plan.reachable?`${duration(plan.minutes)} • พลังงาน −${plan.energy} • โอกาสพบเหตุการณ์ระหว่างทาง ~${risk}`:esc(plan.blocked?`เส้นทางถูกปิดโดย${plan.blocked.type==='flood'?'น้ำหลาก':'ต้นไม้ล้ม'} • ลองเลือกเส้นทางอื่น`:'พื้นที่นี้ไปไม่ถึงจากตำแหน่งปัจจุบัน')}</small></div>`);
  if(plan.reachable&&plan.nextHop&&selected.id!==G.location){const next=D.sites.find(x=>x.id===plan.nextHop),reason=E.available(G,'travel',plan.nextHop);detail.querySelector('button[data-action="travel"]').dataset.id=plan.nextHop;detail.querySelector('button[data-action="travel"]').innerHTML=icon('compass')+(plan.path.length>2?`เดินทางขั้นแรก → ${next.name}`:`เดินทางไป${selected.name}`);detail.querySelector('button[data-action="travel"]').disabled=Boolean(reason);detail.querySelector('button[data-action="travel"]').title=reason||`ไป${next.name}ก่อน • ${duration(E.cost(G,'travel')[0])}`;}
  const routeEdges=new Set(plan.path.slice(1).map((id,i)=>[plan.path[i],id].sort().join('|')));let lineIndex=0;
  for(const a of D.sites)for(const b of a.links)if(a.id<b){const line=wrap.querySelectorAll('line')[lineIndex++],key=[a.id,b].sort().join('|');if(routeEdges.has(key)){line.setAttribute('stroke','#d5e6aa');line.setAttribute('stroke-width','1.2');line.setAttribute('stroke-dasharray','2 1');}}
}
function renderActivity(){
const previousFocus=document.activeElement;
const focusSelector=$('activityContent').contains(previousFocus)&&previousFocus.matches('button')?['action','id','use','item','location','craftfilter','invfilter'].filter(k=>previousFocus.dataset[k]!==undefined).map(k=>`[data-${k}="${CSS.escape(previousFocus.dataset[k])}"]`).join(''):'';
let html='';const [,,tabName,tabHint]=tabs.find(t=>t[0]===tab);$('activityTitle').innerHTML=`${esc(tabName)} <small>${esc(tabHint)}</small>`;
if(tab==='gather'){
const c=E.camp(G),site=G.location,lm=D.landmarks[site],hiddenHere=!G.world.discovered.includes(site),desc={forage:`ผลไม้ 2–3 • อาหารในพื้นที่ ${c.stock}/6`,hunt:`เนื้อ 2–4 • สำเร็จ ${Math.round(WorldRules.huntChance(G)*100)}% • รอยสัตว์ ${c.wildlife}/6`,fish:`ปลาเหลือ ${c.fishStock}/6 • ตกซ้ำทำให้ปลาลดลง`,water:`น้ำจากลำธาร ${WorldRules.flooded(G)?1:3} หน่วย • ต้องทำให้สะอาด`,explore:hiddenHere&&lm?'มีเบาะแสจุดสำรวจพิเศษที่นี่ • หาชิ้นส่วนกู้ภัย • เสี่ยงบาดเจ็บ':'หาวัสดุ ชิ้นส่วนกู้ภัย • เสี่ยงบาดเจ็บ'},byId=Object.fromEntries(actions.map(a=>[a[0],desc[a[0]]?[...a.slice(0,3),desc[a[0]]]:a])),sleepReason=E.available(G,'sleep');
html=`${G.time>=1200?`<div class="inline-warning">${icon('sleep')}ใกล้ 22:00 แล้ว เตรียมอาหาร น้ำ และไฟก่อนเข้านอน</div>`:''}${actionGroups.map(([gk,gi,gn,gd,ids])=>`<section class="action-group" aria-labelledby="group-${gk}"><div class="group-head"><h3 id="group-${gk}">${icon(gi)}${gn}</h3><span>${gd}</span></div><div class="action-grid">${ids.map(id=>actionCard(byId[id])).join('')}${gk==='explore'?`<button class="action-card sleep-card" data-open-sleep ${sleepReason?'disabled':''} title="${esc(sleepReason||'ดูสรุปก่อนเข้านอน')}"><span class="card-top">${icon('tent','card-icon')}<span class="card-arrow" aria-hidden="true">${sleepReason?'':'→'}</span></span><span class="action-title">นอนพักข้ามคืน</span><span class="action-desc">ฟื้นพลังงานเต็มที่ • ข้ามไป 07:00 วันถัดไป</span><span class="card-cost">${sleepReason?`<span class="locked">${esc(sleepReason)}</span>`:`<span>${icon('sleep')}ถึงเช้า</span>`}</span></button>`:''}</div></section>`).join('')}<p class="activity-note">${icon('help')}ของที่แบกไม่ไหวจะฝากในคลังของพื้นที่ • สำรวจและหาอาหารอาจพบเหตุการณ์</p>`;
}else if(tab==='craft'){
html=`<div class="filter-row">${[['camp','แคมป์'],['tool','เครื่องมือ'],['medical','ยา / การรักษา'],['exploration','อุปกรณ์สำรวจ'],['fire','ไฟ / ทำอาหาร']].map(([k,n])=>`<button class="filter ${craftFilter===k?'active':''}" data-craftfilter="${k}">${n}</button>`).join('')}</div>`;
if(craftFilter==='fire'&&E.count(G,'water_filter'))html+=`<div class="portable-filter">${actionCard(['filter','water','กรองน้ำพกพา','น้ำสะอาดสูงสุด 2 • ไม่ใช้ไฟ'])}</div>`;
if(craftFilter==='fire')html+=`<div class="section-description"><span>ไฟคงเหลือ ${duration(E.camp(G).fire)} • เติมไม้ฟืนครั้งละ 2</span></div><div class="action-grid">${[['fire','fire','จุดไฟ / เติมฟืน','ไฟ +4 ชม. • กลางฝนเหลือ 2–3 ชม. ถ้าไม่มีเพิง'],['boil','water','ต้มน้ำ','น้ำจากลำธาร → น้ำสะอาด สูงสุด 3'],['cook','food','ย่างเนื้อ','เนื้อสด → เนื้อย่าง สูงสุด 2'],['dry','food','รมควันเนื้อ','เนื้อสด → เนื้อรมควัน สูงสุด 2']].map(actionCard).join('')}</div>`;
else html+=`<div class="action-grid">${Object.entries(D.recipes).filter(([,r])=>r.group===craftFilter).map(([k,r])=>{const reason=E.available(G,'craft',k),built=r.group==='camp'&&E.camp(G).structures.includes(k);return `<article class="action-card recipe-card"><span class="card-top">${icon(r.icon,'card-icon')}${built?'<span class="condition">สร้างแล้ว</span>':''}</span><strong class="action-title">${r.name}</strong><span class="action-desc">${r.desc}</span><div class="materials">${Object.entries(r.mats).map(([id,n])=>`<span class="material ${E.count(G,id)<n?'missing':''}" title="${esc(D.items[id].name)}">${icon(D.items[id].icon)}${D.items[id].name} ${E.count(G,id)}/${n}</span>`).join('')}</div><div class="recipe-bottom"><span>${duration(r.time)} · ⚡ ${r.energy}</span>${built?`<button class="button quiet" data-dismantle="${k}">รื้อ</button>`:`<button class="button ${reason?'':'primary'}" data-action="craft" data-id="${k}" ${reason?'disabled':''} title="${esc(reason||r.name)}">${reason?(reason==='วัสดุไม่ครบ'?'ขาดวัสดุ':'ยังทำไม่ได้'):'ลงมือทำ'}</button>`}</div>${reason&&reason!=='วัสดุไม่ครบ'&&!built?`<span class="micro">${esc(reason)}</span>`:''}</article>`;}).join('')}</div>`;
if(craftFilter==='camp')html=ExpeditionUI.maintenance(G,icon)+html;
html+=`<p class="activity-note">${icon('pin')}โครงสร้างอยู่ประจำพื้นที่ • รื้อได้วัสดุคืน 50% ปัดเศษลง • เครื่องมือสึกหรอเมื่อใช้งาน</p>`;
}else if(tab==='inventory'){
const weight=E.weight(G),cap=E.capacity(G);html=`<div class="section-description"><strong>สัมภาระของคุณ</strong><span>${weight.toFixed(1)} / ${cap} กก. ${weight>cap*.8?'• เดินทางช้าลง':''}</span></div><div class="pack-meter"><i style="width:${Math.min(100,weight/cap*100)}%"></i></div><div class="filter-row">${[['all','ทั้งหมด'],['food','อาหาร'],['water','น้ำ'],['material','วัสดุ'],['tool','อุปกรณ์'],['cache','คลังพื้นที่']].map(([k,n])=>`<button class="filter ${invFilter===k?'active':''}" data-invfilter="${k}">${n}</button>`).join('')}</div>`;
const source=invFilter==='cache'?E.camp(G).cache:G.inv,entries=Object.entries(source).filter(([id,n])=>n>0&&(invFilter==='all'||invFilter==='cache'||D.items[id].type===invFilter));
html+=entries.length?`<div class="inventory-list">${entries.map(([id,n])=>{const a=D.items[id],consumable=['food','water','medical'].includes(a.type);return `<div class="inventory-row">${icon(a.icon)}<div class="item-description"><strong>${a.name}</strong><small>${a.desc}${a.durability?` • คงเหลือ ${G.tools[id]||a.durability}/${a.durability}`:''}</small></div><span class="item-count">×${n}</span><div class="item-actions">${invFilter==='cache'?`<button class="button" data-action="take" data-id="${id}" ${E.available(G,'take',id)?'disabled':''}>หยิบ 1</button><button class="button quiet" data-item="${id}" data-itemsource="cache">เลือกจำนวน</button>`:`${consumable?`<button class="button" ${E.available(G,'consume',id)?'disabled':''} data-use="${id}">${a.type==='water'?'ดื่ม':a.type==='medical'?'รักษา':'กิน'}</button>`:''}<button class="icon-button" data-item="${id}" aria-label="จัดการ${a.name}">${icon('settings')}</button>`}</div></div>`;}).join('')}</div>`:`<div class="empty-state">${icon('pack')}${invFilter==='cache'?'คลังในพื้นที่นี้ยังว่าง ฝากของไว้เพื่อเดินทางเบาขึ้น':'ยังไม่มีของในหมวดนี้'}</div>`;
html+=`<p class="activity-note">${icon('help')}${invFilter==='cache'?`คลังนี้อยู่ที่${E.site(G).name} • อาหารสดในคลังก็เน่าเสียข้ามคืน`:'กิน ดื่ม และจัดกระเป๋าไม่ใช้เวลา • อาหารให้พลังงานเพิ่ม 3 • เก็บชิ้นส่วนกู้ภัยไว้กับตัว'}</p>`;
}else if(tab==='map'){
if(!D.sites.some(x=>x.id===mapSelected))mapSelected=G.location;
const selected=D.sites.find(x=>x.id===mapSelected),current=E.site(G),edges=[];
for(const a of D.sites)for(const b of a.links)if(a.id<b){const dest=D.sites.find(x=>x.id===b);edges.push(`<line x1="${a.x}" y1="${a.y}" x2="${dest.x}" y2="${dest.y}" stroke="${WorldRules.blocked(G,a.id,b)?'#dc997c':[a.id,b].includes(G.location)?'#a4ba83':'#69805c'}" stroke-dasharray="1 1.4"/>`);}
html=`<div class="section-description"><strong>ภูมิประเทศ / Northern Highlands</strong><span>สำรวจแล้ว ${G.visited.length}/7 พื้นที่</span></div><div class="map-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${[0,1,2,3,4,5,6].map(i=>`<path d="M ${-10+i*5} 100 Q ${15+i*3} 80 ${10+i*6} 50 T ${40+i*6} -10" stroke="#a4b77e20" fill="none"/>`).join('')}${edges.join('')}</svg>${D.sites.map(a=>`<button class="map-node ${a.id===G.location?'current':''} ${a.id===mapSelected?'selected':''} ${G.visited.includes(a.id)?'':'unvisited'}" style="left:${a.x}%;top:${a.y}%" data-location="${a.id}" aria-label="${a.name}${a.id===G.location?' ตำแหน่งปัจจุบัน':''}"><i>${icon(a.id===G.location?'pin':a.quest?'signal':a.water?'water':'mountain')}</i><span>${a.name}</span></button>`).join('')}<div class="map-compass">N${icon('compass')}</div></div><div class="map-details"><div><h3>${selected.name} ${selected.id===G.location?'<span class="condition">คุณอยู่ที่นี่</span>':''}</h3><p>${selected.resource} • ${selected.alt} ม.</p><p>${current.links.includes(selected.id)?`เดินทาง ${duration(E.cost(G,'travel')[0])} • พลังงาน −${E.cost(G,'travel')[1]}`:selected.id===G.location?'เลือกพื้นที่ที่เชื่อมต่อเพื่อเดินทาง':'เดินผ่านพื้นที่ที่เชื่อมต่อก่อน'}</p></div><button class="button primary" data-action="travel" data-id="${selected.id}" ${E.available(G,'travel',selected.id)?'disabled':''} title="${esc(E.available(G,'travel',selected.id))}">${icon('compass')}เดินทาง</button></div>`;
}else if(tab==='quest'){
const first=[['tent','สร้างเพิงพัก','ไม้ 6 + เส้นใย 6',Boolean(G.milestones.shelter),'data-nav="craft" data-navfilter="camp"'],['fire','ก่อหลุมไฟ','ไม้ 3 + หิน 4',Boolean(G.milestones.firepit),'data-nav="craft" data-navfilter="camp"'],['water','สำรวจแหล่งน้ำ','ลำธารหรือหุบเขาหมอก',G.visited.includes('river')||G.visited.includes('valley'),'data-nav="map" data-navmap="river"']];
html=`<section class="quest-panel first-steps"><div class="panel-title"><h2>${icon('tent')} ภารกิจ 01 • ตั้งหลักก่อนตะวันลับ</h2><span class="micro">${first.filter(x=>x[3]).length}/3</span></div><ol class="step-list">${first.map(([i,n,d,done,go])=>`<li class="${done?'done':''}"><span class="step-check">${icon(done?'check':i)}</span><span><strong>${n}</strong><small>${d}</small></span>${done?'<span class="condition">สำเร็จ</span>':`<button class="button" ${go}>ไปทำ ${icon('arrow')}</button>`}</li>`).join('')}</ol></section><section class="quest-panel"><div class="panel-title"><h2>${icon('signal')} ภารกิจกู้ภัย • สัญญาณสุดท้าย</h2><span class="micro">${['radio','battery','wire'].filter(k=>E.count(G,k)).length}/3 ชิ้น</span></div><p>ใช้ «สำรวจเส้นทาง» ในสถานีร้าง หุบเขาหมอก และสันเขา เพื่อหาชิ้นส่วน จากนั้นส่งสัญญาณที่สันเขาตั้งแต่วันที่ 10 ในวันที่ไม่มีพายุ</p><div class="quest-parts">${['radio','battery','wire'].map(id=>`<div class="quest-part ${E.count(G,id)?'found':''}">${icon(D.items[id].icon)}${D.items[id].name}${E.count(G,id)?' ✓':''}</div>`).join('')}</div><button class="button primary" data-action="signal" ${E.available(G,'signal')?'disabled':''}>${icon('signal')}${E.available(G,'signal')||'ส่งสัญญาณขอความช่วยเหลือ • 2 ชม. / พลังงาน 18'}</button></section>${journeyGoalsHTML()}${ExpeditionUI.atlas(G,icon)}`;
}else html=`<div class="section-description"><strong>บันทึกการเดินทาง</strong><span>${G.actions} กิจกรรม • ${G.logs.length} บันทึกล่าสุด</span></div><div class="journal-list">${G.logs.map(logHTML).join('')}</div>`;
if(tab==='inventory'&&E.count(G,'water_filter'))html+=`<div class="portable-filter">${actionCard(['filter','water','กรองน้ำพกพา','น้ำสะอาดสูงสุด 2 • ไม่ใช้ไฟ'])}</div>`;
if(tab==='gather'){const hazardsSoon=WorldRules.active(G).length||(G.day>=4&&G.weather==='storm')||WorldRules.hazardsFor(G,G.forecast,G.day+1).length||(G.day>=3&&G.forecast==='storm'),landmarkReady=G.world.discovered.includes(G.location)&&!G.world.claimed.includes(G.location),hard=G.difficulty==='wild';html=(hazardsSoon&&(!hard||SurvivalAdvice.next(G)?.critical)?ExpeditionUI.outlook(G,icon):'')+html+(landmarkReady&&!hard?ExpeditionUI.landmark(G,G.location,icon):'');}
if(tab==='map')html=ExpeditionUI.outlook(G,icon)+html+ExpeditionUI.landmark(G,mapSelected,icon);
$('activityContent').innerHTML=html;
if(tab==='map')enhanceMapPlanning();
if(focusSelector){const nextFocus=$('activityContent').querySelector(focusSelector);if(nextFocus&&!nextFocus.disabled)nextFocus.focus({preventScroll:true});}
}
function showGuide(){openModal('ป่าไม่รีบ แต่คุณต้องวางแผน',`<p>คุณหลงทางในแนวเขาทางเหนือ เป้าหมายคืออยู่รอดครบ <b>30 วัน</b> หรือประกอบวิทยุเพื่อให้ทีมค้นหาพบคุณตั้งแต่วันที่ 10</p>${[
['01','ตั้งหลักในวันแรก','เก็บไม้และเส้นใย แล้วสร้างเพิงพัก (ไม้ 6 + เส้นใย 6) จากนั้นสร้างหลุมกองไฟ (ไม้ 3 + หิน 4) ในเมนูสร้าง'],
['02','ให้ความสำคัญกับน้ำ','ไปลำธารจากแผนที่ เก็บน้ำ แล้วใช้กองไฟต้มครั้งละ 3 หน่วย อาหารและน้ำใช้ได้ในกระเป๋า ค่าที่มากหมายถึงร่างกายที่พร้อมกว่า'],
['03','เตรียมตัวสำหรับกลางคืน','นอนได้ตั้งแต่ 15:00 และกิจกรรมสิ้นสุดที่ 22:00 กินและดื่มก่อนนอน ไฟเหลืออย่างน้อย 2 ชม. จะช่วยผ่านคืนหนาว เพิงพักและที่นอนช่วยฟื้นแรง'],
['04','ดูแลอุปกรณ์และแคมป์','ขวาน หอก เบ็ดมีอายุใช้งาน ของหนักทำให้เดินช้าลง ฝากของได้ในคลังแต่ละพื้นที่ อาหารสดเน่าเสียข้ามคืน ใช้ราวรมควันเก็บเนื้อได้นาน'],
['05','อ่านสัญญาณจากป่า','ตั้งแต่วันที่ 4 น้ำหลากและต้นไม้ล้มอาจปิดทาง อ่านคำเตือนก่อนเดินทาง ใช้ขวานเปิดทางหรือเดินอ้อม ค้ำยันแคมป์ก่อนพายุ และซ่อมเมื่อความแข็งแรงต่ำกว่า 40%'],
['06','ค้นหาอุปกรณ์เฉพาะทาง','สำรวจเส้นทางเพื่อเปิดเบาะแสทั้ง 7 พื้นที่ แล้วเข้าสำรวจรับอุปกรณ์พิเศษ ถ้ำต้องใช้คบไฟ น้ำตกต้องใช้เชือกปีน สร้างได้ในหมวดอุปกรณ์สำรวจ'],
['07','ตามหาทางกลับบ้าน','สำรวจสถานีร้างเพื่อหาวิทยุ หุบเขาหมอกเพื่อหาแบตเตอรี่ และสันเขาเพื่อหาสายสัญญาณ ระวังฝน ความเปียก อุบัติเหตุ และเหตุการณ์ระหว่างทาง']
].map(([n,t,d])=>`<div class="guide-step"><span>${n}</span><div><strong>${t}</strong><p>${d}</p></div></div>`).join('')}<p>ค่าร่างกายต่ำกว่า 25 คือสัญญาณเตือน • ยารักษาป่วยและแผล • อาการหายเองใน 2 คืน แต่จะเสียสุขภาพระหว่างนั้น</p><p><span class="kbd">1–6</span> เปลี่ยนเมนู <span class="kbd">?</span> คู่มือ <span class="kbd">Esc</span> ปิดหน้าต่าง • เกมหยุดเวลาเมื่อคุณไม่ลงมือ</p><div class="modal-actions"><button class="button primary" data-close>พร้อมออกสำรวจ ${icon('arrow')}</button></div>`,'normal','SURVIVAL HANDBOOK');}
function showSleep(){
  const reason=E.available(G,'sleep');if(reason)return toast(reason);
  const c=E.camp(G),p=E.sleepPreview(G),round=n=>Math.round(n),range=p.healthMin!==p.health?`${round(p.healthMin)}–${round(p.health)}`:String(round(p.health));
  const stats=[['food','food','ความอิ่ม',p.food,10],['water','water','น้ำในร่างกาย',p.water,10],['warmth','temp','ความอบอุ่น',p.warmth,22],['energy','energy','พลังงาน',p.energy,10],['health','heart','สุขภาพ',p.healthMin,25]];
  const critical=p.healthMin<25||p.food<10||p.water<10||p.warmth<22;
  const risks=p.causes.map(cause=>`<li>${esc(cause.label)} <span>สุขภาพ −${Number(cause.damage.toFixed(1))}</span></li>`).join('');
  const campRisk=G.day>=4&&(G.weather==='storm'||WorldRules.flooded(G))&&c.structures.length;
  openModal('ก่อนคืนนี้จะมาถึง',`<p>${G.day===30?'ผ่านคืนสุดท้ายเพื่อให้ทีมค้นหาพบคุณ':'พักจนถึง 07:00 น. วันถัดไป'} • อาหารสดบางส่วนจะเน่าเสีย</p><h3 class="projection-title">ค่าร่างกายหลังพักโดยประมาณ</h3><div class="sleep-projection">${stats.map(([key,i,label,value,threshold])=>`<div class="projection-stat ${value<threshold?'at-risk':''} ${key==='health'?'projection-health':''}"><span>${icon(i)}${label}</span><strong>${round(G[key])} <small>→</small> ${key==='health'?range:round(value)}</strong><small>/ 100</small></div>`).join('')}</div>${risks?`<div class="sleep-risks"><strong>ปัจจัยที่ทำให้เสียสุขภาพคืนนี้</strong><ul>${risks}</ul></div>`:`<p class="micro">ไม่มีการเสียสุขภาพจากอาหาร น้ำ ความหนาว หรืออาการป่วยตามสภาพปัจจุบัน</p>`}${p.attackRisk?`<p class="micro">นอนกลางแจ้ง: โอกาสเจอสัตว์ป่า ${Number((p.attackRisk*100).toFixed(1))}% • เสียสุขภาพเพิ่ม ${Number((8*D.difficulties[G.difficulty].decay).toFixed(1))} • ช่วงสุขภาพรวมความเสี่ยงนี้แล้ว</p>`:''}<div class="sleep-context"><span>${p.shelter?'มีเพิงพักที่ใช้งานได้':'นอนกลางแจ้ง / เพิงพักใช้ไม่ได้'}</span><span>${p.fire?'ไฟพอให้โบนัสความอบอุ่น':'ไฟต่ำกว่า 2 ชม. ไม่มีโบนัสกลางคืน'}</span></div>${campRisk?`<p class="inline-warning">คืนนี้แคมป์เสี่ยงเสียหาย • ความแข็งแรง ${c.condition}% • ${c.braced?'ค้ำยันแล้ว':'ยังไม่ค้ำยัน'}</p>`:''}${p.health===0?'<p class="inline-warning">จากสภาพปัจจุบัน คุณจะไม่รอดคืนนี้</p>':p.healthMin===0?'<p class="inline-warning">หากเจอสัตว์ป่าคืนนี้ คุณอาจไม่รอด</p>':''}<p class="micro">ค่าคำนวณจากการเข้านอนตอนนี้ • คืนนี้ ${D.weather[G.weather].name} / พรุ่งนี้ ${D.weather[G.forecast].name}</p>${G.difficulty!=='wild'||critical?`<div class="sleep-preparation"><button class="text-button" data-nav="inventory" data-navfilter="all">ดูเสบียงและยา →</button><button class="text-button" data-nav="craft" data-navfilter="camp">ดูแคมป์ →</button><button class="text-button" data-nav="craft" data-navfilter="fire">ดูไฟและน้ำ →</button></div>`:''}<div class="modal-actions"><button class="button quiet" data-close>${G.difficulty==='wild'?'กลับ':'เตรียมตัวอีกนิด'}</button><button class="button primary" data-confirm-sleep>${icon('sleep')}เข้านอน</button></div>`,'normal','REST & RECOVER');
}
function showEvent(){
  const stories={
     riverbank:['แอ่งน้ำที่ไม่อยู่ในแผนที่','เสียงน้ำไหลลอดก้อนหินดังผิดจังหวะ แอ่งเล็ก ๆ ตรงหน้าดูใสกว่าลำธารหลัก แต่พื้นลื่นและกระแสน้ำแรงกว่าที่เห็น',[['ลองใช้เบ็ดสำรวจแอ่ง',E.count(G,'rod')&&!WorldRules.flooded(G)&&E.camp(G).fishStock>0?'มีเบ็ด: ได้ปลา 1 • ปลาในพื้นที่ลด 1 • เบ็ดสึกหรอ 1':'จับปลาไม่ได้ • เปียกเพิ่ม 8'],['รองน้ำจากซอกหิน','น้ำไม่สะอาด 1 • เปียกเพิ่ม 4']]],
     forest_call:['เสียงร้องในเรือนยอด','เสียงสัตว์ร้องจากเรือนยอดวนไปตามลม รอยกีบใหม่ตัดผ่านกอเฟิร์น แต่ป่าดิบเริ่มมืดลง',[['ตามรอยเข้าไป',E.count(G,'spear')&&E.camp(G).wildlife>0?'มีหอก: เนื้อสด 1 • รอยสัตว์ลด 1 • หอกสึกหรอ 1':'ไม่ได้อาหาร • พลังงาน −6'],['ทำเครื่องหมายแล้วเก็บเส้นใย','ได้เส้นใย 2 • ปลอดภัย']]],
    cave_echo:['เสียงสะท้อนใต้ผาหิน','เสียงหยดน้ำในถ้ำสะท้อนกลับมาเป็นจังหวะ คล้ายมีห้องว่างอยู่ลึกเข้าไป',[['เข้าไปดูด้วยคบไฟ',E.count(G,'torch')?'ใช้คบไฟ 1: ได้เศษโลหะ 2 และยา 1':'ไม่มีคบไฟ: เสี่ยงบาดเจ็บและเสียสุขภาพ 8'],['จำตำแหน่งไว้แล้วถอยกลับ','ปลอดภัย • พลังงาน +4']]],
     radio_static:['เสียงซ่าจากสถานีร้าง','วิทยุเก่าบนโต๊ะส่งเสียงซ่าเป็นช่วง ๆ สัญญาณสั้น ๆ อาจเป็นเบาะแสของห้องเก็บของ',[['นั่งฟังและจดทิศทาง','พลังงาน −5 • สำรวจจุดพิเศษที่สถานีเร็วขึ้น 30 นาทีและใช้พลังงานลด 4'],['งัดแผงโลหะข้างสถานี','ได้เศษโลหะ 2']]],
     fog_signal:['แสงวาบในหุบเขาหมอก','แสงสีอุ่นวาบอยู่หลังม่านหมอก มันอาจเป็นโลหะสะท้อนแสงจากซากเครื่องบิน',[['ตามแสงเข้าไป','พลังงาน −4 • เปียกเพิ่ม 12 • สำรวจจุดพิเศษในหุบเขาเร็วขึ้น 30 นาทีและใช้พลังงานลด 4'],['หลบหมอกและเก็บสมุนไพร','ได้สมุนไพร 2 • ปลอดภัย']]],
    ridge_beacon:['ลมแรงบนสันเขา','แผ่นสะท้อนแสงเก่าติดอยู่บนเสา ธงขาด ๆ ยังชี้ไปทางท้องฟ้าเปิด',[['จุดแผ่นสะท้อนแสง','พลังงาน −4 • ความอบอุ่น +8'],['พักใต้แนวหิน','พลังงาน +4 • ปลอดภัย']]],
    old_camp:['ร่องรอยแคมป์เก่า','ใต้กองใบไม้มีวงหินเก่าและกล่องผุพัง เจ้าของเดิมคงรีบออกไปก่อนฤดูฝน',[['เปิดกล่องอย่างระวัง','เสบียง 1 และเศษโลหะ 1'],['เก็บเส้นใยแห้งแล้วไปต่อ','ได้เส้นใย 2 • ปลอดภัย']]],
    tracks:['รอยเท้าที่เพิ่งผ่านไป','กิ่งไม้ข้างหน้าสั่นไหว รอยกีบใหม่บนดินชื้นอาจพาไปถึงอาหาร… หรือเจ้าของรอยเท้าที่ยังอยู่ใกล้ ๆ',[['ตามรอยอย่างเงียบ ๆ',E.count(G,'spear')?'มีหอก: ได้เนื้อสด 2 • หอกสึกหรอ 1':'สำเร็จ 55%: เนื้อสด 2 • พลาด: สุขภาพ −12 และบาดแผล'],['อ้อมออกมา','ไม่มีความเสี่ยง • พลังงาน +4']]],
    backpack:['กระเป๋าเหนือชะง่อนหิน','คุณเห็นกระเป๋านักเดินทางเก่าติดอยู่บนกิ่งไม้เหนือทางชัน ผ้าขาดวิ่น แต่ของด้านในอาจยังใช้ได้',[['ปีนขึ้นไปเอา','เสบียง 2 + เศษโลหะ 2 • เสี่ยงบาดเจ็บ 30% (สุขภาพ −8)'],['เก็บของใกล้ทางแล้วไปต่อ','ได้เส้นใย 2 • ปลอดภัย']]],
    rainfront:['ฝนไล่หลังมาแล้ว','เสียงฝนกระทบเรือนยอดใกล้เข้ามาอย่างรวดเร็ว ชะง่อนหินด้านหนึ่งพอหลบได้ อีกด้านมีน้ำไหลจากใบไม้',[['เข้าไปหลบฝน','พลังงาน −6 • ความเปียก −20'],['ใช้โอกาสนี้รองน้ำ','น้ำไม่สะอาด 2 • ความเปียก +20']]],
    snake:['เงาเลื้อยบนทางเดิน','งูตัวหนึ่งขวางอยู่บนหินอุ่น มันยังไม่ทันเห็นคุณ ระยะห่างระหว่างคุณกับมันสั้นกว่าที่คิด',[['ค่อย ๆ ถอยห่าง','ปลอดภัย • พลังงาน −8'],['ใช้กิ่งไม้หรือหอกไล่ต้อน',E.count(G,'spear')?'มีหอก: เนื้อสด 1 • หอกสึกหรอ 1':'เนื้อสด 1 • เสี่ยงถูกกัด 35%: สุขภาพ −10 และป่วย']]],
    ravine:['ทางลัดเหนือร่องเขา','ลำต้นที่ล้มพาดร่องเขาดูเหมือนจะช่วยย่นระยะทางได้ แต่เปลือกไม้ชื้นลื่นใต้รองเท้า',[['ลองข้ามทางลัด','พลังงาน +10 • เสี่ยงลื่น 25%: สุขภาพ −14 และแผล'],['เดินอ้อมตามสันดิน','ปลอดภัย • พลังงาน −4']]],
    herbgrove:['สมุนไพรในดงหนาม','กลิ่นใบสมุนไพรที่คุณคุ้นเคยลอยมาจากกลางดงหนาม ใกล้ ๆ กันมีผลไม้เล็กน้อยบนกิ่งต่ำ',[['ฝ่าเข้าไปเก็บสมุนไพร','สมุนไพร 3 • เสี่ยงหนามบาด 20%: สุขภาพ −5 และแผล'],['เก็บผลไม้ริมทาง','ผลไม้ป่า 1 • ปลอดภัย']]]
  };
  const story=stories[G.event]||['สัญญาณที่อ่านไม่ออก','ป่าทิ้งร่องรอยบางอย่างไว้ให้คุณตัดสินใจ',[['สำรวจต่อ','เดินหน้าต่ออย่างระวัง'],['ถอยกลับ','รักษาพลังงานไว้']]], [title,desc,choices]=story;
  openModal(title,`<p>${desc}</p>${choices.map(([n,d],i)=>`<button class="event-choice ${["riverbank","forest_call","cave_echo","radio_static","fog_signal","ridge_beacon","old_camp"].includes(G.event)?'regional-event':''}" data-choice="${i}"><strong>${n} ↗</strong><small>${d}</small></button>`).join('')}<p class="micro">เหตุการณ์เป็นส่วนหนึ่งของกิจกรรมที่ผ่านมา จึงไม่ใช้เวลาเพิ่ม</p>`,'event',["riverbank","forest_call","cave_echo","radio_static","fog_signal","ridge_beacon","old_camp"].includes(G.event)?'A TRACE OF THIS PLACE':'AN UNEXPECTED ENCOUNTER');
}
function showEnd(){openModal(G.won?'ป่าจำคุณได้ และคุณได้กลับบ้าน':'เรื่องราวของคุณจบลงที่นี่',`<div class="end-symbol">${icon(G.won?'signal':'leaf')}</div><p class="center">${G.won?(G.signal?'เสียงใบพัดดังขึ้นเหนือแนวสน คุณยกมือขึ้นเป็นครั้งแรกโดยไม่ต้องกลัวสิ่งใด':'สามสิบวันที่เปลี่ยนคุณไปตลอดกาล ทีมค้นหาพบแคมป์ของคุณแล้ว'):'คุณทำดีที่สุดในเส้นทางครั้งนี้แล้ว ลองใหม่ พร้อมบทเรียนจากป่า'}</p><div class="end-summary"><div><strong>${G.day}</strong><small>วันที่อยู่รอด</small></div><div><strong>${G.visited.length}/7</strong><small>พื้นที่สำรวจ</small></div><div><strong>${G.actions}</strong><small>การตัดสินใจ</small></div></div><div class="modal-actions"><button class="button quiet" data-end-journal>อ่านบันทึก</button><button class="button primary" data-newgame>เริ่มการเดินทางใหม่ ${icon('arrow')}</button></div>`,'end',G.won?'YOU MADE IT HOME':'END OF EXPEDITION');}
function slotKey(n){return `wildland_slot_${n}_v2`;}
function readSlot(n){try{const raw=localStorage.getItem(slotKey(n));if(raw===null)return null;return E.validate(JSON.parse(raw));}catch(error){return {invalid:true,error:error.message};}}
function writeSlot(n){try{localStorage.setItem(slotKey(n),JSON.stringify(G));settings();toast(`บันทึกลงช่อง ${n} แล้ว`);}catch(error){toast('บันทึกช่องไม่สำเร็จ • กรุณาส่งออกไฟล์เซฟ');}}
function settings(){
   const slots=[1,2,3].map(n=>{const data=readSlot(n),valid=data&&!data.invalid;return `<article class="save-slot ${data?'filled':''}"><div><strong>ช่อง ${n}</strong><small>${valid?`วันที่ ${data.day} เวลา ${time(data.time)} • ${E.site(data).name}`:data?.invalid?'ไฟล์ช่องนี้อ่านไม่ได้':'ยังว่าง'}</small></div><div class="slot-actions"><button class="button" data-slot-save="${n}">${data?'บันทึกทับ':'บันทึกช่องนี้'}</button><button class="button quiet" data-slot-load="${n}" ${valid?'':'disabled'}>โหลด</button></div></article>`;}).join('');
  openModal('เตรียมพร้อมสำหรับการเดินทาง',`<div class="setting-row"><div>บันทึกอัตโนมัติ<small>${storageWorks?'บันทึกในเครื่องหลังทุกกิจกรรม':'บันทึกในเครื่องไม่ได้ กรุณาส่งออกไฟล์เซฟ'}</small></div><span class="condition">${storageWorks?'ทำงานอยู่':'ไม่พร้อม'}</span></div><section class="save-slots"><div class="panel-title"><h2>${icon('save')} ช่องบันทึกการเดินทาง</h2><span class="micro">เลือกเก็บความคืบหน้าได้ 3 ช่อง</span></div>${slots}</section><div class="setting-row"><div>จุดบันทึกเดิม<small>ระบบเดิมยังใช้งานได้ แยกจากช่องบันทึกด้านบน</small></div><button class="button" data-checkpoint>${icon('save')}บันทึก</button><button class="button" data-load>โหลด</button></div><div class="setting-row"><div>ไฟล์เซฟ .json<small>ย้ายการเดินทางไปยังแอป เบราว์เซอร์ หรือเครื่องอื่น</small></div><button class="button" data-export>ส่งออก</button><button class="button" data-import>นำเข้า</button></div><div class="setting-row"><div>เสียงเกม<small>เสียงกิจกรรม ลม และนก • หยุดเมื่อสลับออกจากเกม</small></div><button class="button" data-sound>${ambience.active?'ปิดเสียง':'เปิดเสียง'}</button></div><div class="setting-row sound-level"><div><label for="effectsVolume">ความดังเสียงกิจกรรม</label><small>ปรับแยกจากเสียงธรรมชาติ</small></div><input id="effectsVolume" type="range" min="0" max="100" step="5" value="${Math.round(effectsVolume*100)}" aria-label="ความดังเสียงกิจกรรม"><output id="effectsVolumeValue" for="effectsVolume">${Math.round(effectsVolume*100)}%</output></div><div class="modal-actions"><button class="button" data-preview-sound>ฟังตัวอย่างเสียง</button></div><p class="micro">เซฟเกมเดิมรุ่น 1 ใช้กับระบบใหม่ไม่ได้ และยังอยู่ในไฟล์เดิมของคุณ</p><div class="modal-actions"><button class="button danger" data-newgame>เริ่มเกมใหม่ / เลือกความยาก</button></div>`,'settings','EXPEDITION SETTINGS');
  $('effectsVolume').closest('.setting-row').insertAdjacentHTML('afterend',`<div class="setting-row sound-level"><div><label for="natureVolume">ความดังเสียงธรรมชาติ</label><small>ลม ฝน และนก</small></div><input id="natureVolume" type="range" min="0" max="100" step="5" value="${Math.round(natureVolume*100)}" aria-label="ความดังเสียงธรรมชาติ"><output id="natureVolumeValue" for="natureVolume">${Math.round(natureVolume*100)}%</output></div>`);
}
function newGameDialog(){openModal('เลือกเส้นทางของคุณ',`<p>เริ่มต้นวันแรกพร้อมสัมภาระชุดใหม่ การเดินทางปัจจุบันจะถูกแทนที่ คุณสามารถส่งออกเซฟจากหน้าตั้งค่าก่อนเริ่มใหม่ได้</p>${Object.entries(D.difficulties).map(([id,d])=>`<button class="difficulty-card" data-difficulty="${id}"><strong>${d.name}${id==='survivor'?' / แนะนำ':''} ↗</strong><small>${d.desc}</small></button>`).join('')}`,'normal','A NEW EXPEDITION');}
function itemDialog(id,source='inventory'){
  const a=D.items[id],cached=source==='cache';
  if(a.type==='quest'&&!cached)return openModal(a.name,`<p>${esc(a.desc)}</p><p>ชิ้นส่วนกู้ภัยจะเก็บติดตัวไว้เสมอ</p>`);
  openModal(a.name,`<p>${esc(a.desc)}</p><p>น้ำหนัก ${a.weight} กก./ชิ้น • ในกระเป๋า ${E.count(G,id)} • ในคลัง ${E.camp(G).cache[id]||0}</p><div class="transfer-controls" data-transfer-item="${id}"><label for="transferType">การจัดการ</label><select id="transferType">${cached?'<option value="take">หยิบจากคลังเข้ากระเป๋า</option>':'<option value="stash">ฝากไว้ในคลังพื้นที่นี้</option><option value="drop">ทิ้งสิ่งของ</option>'}</select><label for="transferQuantity">จำนวนชิ้น</label><div class="quantity-row"><input id="transferQuantity" type="number" min="1" step="1" value="1" inputmode="numeric"><button class="button quiet" data-transfer-all>เลือกทั้งหมด</button></div><p id="transferPreview" role="status" aria-live="polite"></p><p class="micro" id="transferNote"></p><div class="modal-actions"><button class="button quiet" data-close>ยกเลิก</button><button class="button primary" data-transfer-confirm>ย้ายสิ่งของ</button></div></div>`,'transfer','PACK & CACHE');
  updateTransferPreview();
}
function updateTransferPreview(){
  const controls=$('modalBody').querySelector('[data-transfer-item]');if(!controls)return;
  const id=controls.dataset.transferItem,type=$('transferType').value,quantity=Number($('transferQuantity').value),plan=E.inventoryPlan(G,type,id,quantity),limit=E.inventoryPlan(G,type,id).max;
  $('transferQuantity').max=String(limit);$('transferQuantity').disabled=limit===0;
  controls.querySelector('[data-transfer-all]').disabled=limit===0;
  $('transferPreview').textContent=plan.ok?`น้ำหนักหลัง${type==='take'?'หยิบ':type==='stash'?'ฝาก':'ทิ้ง'} ${plan.weight.toFixed(1)} / ${plan.capacity} กก.${plan.weight>plan.capacity*.8?' • เดินทางช้าลง':''}`:plan.message;
  $('transferPreview').className=plan.ok?'transfer-preview':'transfer-preview transfer-error';
  $('transferNote').textContent=type==='drop'?'ของที่ทิ้งจะหายไปจากการเดินทาง':`${type==='take'?`หยิบได้สูงสุด ${limit} ชิ้นตามที่ว่างในกระเป๋า`:`ฝากได้สูงสุด ${limit} ชิ้น • คลังอยู่ที่${E.site(G).name}`} • ไม่ใช้เวลา`;
  const confirm=controls.querySelector('[data-transfer-confirm]');confirm.disabled=!plan.ok;confirm.className=`button ${type==='drop'?'danger':'primary'}`;confirm.textContent=`${type==='take'?'หยิบ':type==='stash'?'ฝาก':'ทิ้ง'} ${Number.isInteger(quantity)&&quantity>0?quantity:'—'} ชิ้น`;
}
const actionAudio=createActionAudio();
const natureAudio=createNatureAudio();
let effectsVolume=.65;
try{const stored=localStorage.getItem('wildland_effect_volume_v1');if(stored!==null&&Number.isFinite(Number(stored)))effectsVolume=Math.max(0,Math.min(1,Number(stored)));}catch(e){}
actionAudio.setVolume(effectsVolume);
let natureVolume=.65;
try{const stored=localStorage.getItem('wildland_nature_volume_v1');if(stored!==null&&Number.isFinite(Number(stored)))natureVolume=Math.max(0,Math.min(1,Number(stored)));}catch(e){}
natureAudio.setVolume(natureVolume);
const ambience={active:false,context:null,timer:null,busy:false,
async toggle(){
  if(this.busy)return;
  this.busy=true;
  try{
    if(!this.context){
      this.context=new (window.AudioContext||window.webkitAudioContext)();
      actionAudio.attach(this.context);
      natureAudio.attach(this.context);
      natureAudio.update(G.weather);
    }
    if(!this.active)await this.context.resume();
    this.active=!this.active;
    actionAudio.setEnabled(this.active&&!document.hidden);
    natureAudio.setEnabled(this.active&&!document.hidden);
    if(this.active){actionAudio.play('preview');this.scheduleBird();}
    else clearTimeout(this.timer);
    this.update();
  }catch(e){toast('อุปกรณ์นี้ยังเปิดเสียงไม่ได้');}
  finally{this.busy=false;}
},
scheduleBird(){
  clearTimeout(this.timer);
  if(!this.active)return;
  this.timer=setTimeout(()=>{if(!document.hidden)natureAudio.bird(G);this.scheduleBird();},5000+Math.random()*7000);
},
update(){$('soundButton').innerHTML=icon(this.active?'sound':'muted');$('soundButton').setAttribute('aria-label',this.active?'ปิดเสียงเกม':'เปิดเสียงเกม');$('soundButton').title=this.active?'ปิดเสียงเกม':'เปิดเสียงเกม';$('soundButton').setAttribute('aria-pressed',String(this.active));}
};
document.addEventListener('click',async event=>{
const b=event.target.closest('button');if(!b||b.disabled)return;
if(b.dataset.nav){const nav=b.dataset.nav,filter=b.dataset.navfilter;if(nav==='craft')craftFilter=filter||'camp';if(nav==='inventory')invFilter=filter||'all';if(b.dataset.navmap)mapSelected=b.dataset.navmap;if($('modal').open&&modalMode!=='event')closeModal();setTab(nav,{focus:true});const target=b.dataset.navaction?$('activityContent').querySelector(`[data-action="${b.dataset.navaction}"]${b.dataset.navactionid?`[data-id="${b.dataset.navactionid}"]`:''}`):b.dataset.navitem?$('activityContent').querySelector(`[data-use="${b.dataset.navitem}"], [data-item="${b.dataset.navitem}"], [data-id="${b.dataset.navitem}"]`):null;if(target){target.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});target.focus({preventScroll:true});}return;}
if(b.dataset.tab)return setTab(b.dataset.tab);
if(b.hasAttribute('data-open-sleep'))return showSleep();
if(b.dataset.craftfilter){craftFilter=b.dataset.craftfilter;return renderActivity();}
if(b.dataset.invfilter){invFilter=b.dataset.invfilter;return renderActivity();}
if(b.dataset.location){mapSelected=b.dataset.location;return tab==='map'?renderActivity():setTab('map',{focus:true});}
if(b.dataset.action)return run(b.dataset.action,b.dataset.id);
if(b.hasAttribute('data-close'))return closeModal();
if(b.hasAttribute('data-confirm-sleep')){closeModal();return run('sleep');}
if(b.dataset.choice!==undefined){const previousHealth=G.health;const result=E.resolveEvent(G,Number(b.dataset.choice));actionAudio.play(result.ok?'choice':'error',{hurt:G.health<previousHealth});if(G.ended)actionAudio.play(G.won?'win':'lose');modalMode='';closeModal();save();render();toast(result.message);if(G.ended)showEnd();return;}
if(b.dataset.use){const id=b.dataset.use;if(D.items[id].risk)openModal('ยอมรับความเสี่ยงนี้หรือไม่?',`<p>${D.items[id].name}: ${D.items[id].desc}</p><div class="modal-actions"><button class="button quiet" data-close>กลับไปเตรียมให้สะอาด</button><button class="button danger" data-risk-use="${id}">ใช้ทั้งอย่างนี้</button></div>`);else run('consume',id);return;}
if(b.dataset.riskUse){closeModal();return run('consume',b.dataset.riskUse);}
if(b.dataset.item)return itemDialog(b.dataset.item,b.dataset.itemsource);
if(b.hasAttribute('data-transfer-all')){const id=$('modalBody').querySelector('[data-transfer-item]').dataset.transferItem;$('transferQuantity').value=String(E.inventoryPlan(G,$('transferType').value,id).max);updateTransferPreview();return;}
if(b.hasAttribute('data-transfer-confirm')){const id=$('modalBody').querySelector('[data-transfer-item]').dataset.transferItem,type=$('transferType').value,quantity=Number($('transferQuantity').value),plan=E.inventoryPlan(G,type,id,quantity);if(!plan.ok)return toast(plan.message);closeModal();return run(type,id,quantity);}
if(b.dataset.itemAction){closeModal();return run(b.dataset.itemAction,b.dataset.id);}
if(b.dataset.dismantle){const id=b.dataset.dismantle;openModal(`รื้อ${D.recipes[id].name}`,`<p>ใช้เวลา 30 นาที พลังงาน 8 คืนวัสดุ 50% ปัดเศษลง${id==='shelter'?' ที่นอนใต้เพิงจะถูกรื้อไปด้วย':''}</p><div class="modal-actions"><button class="button quiet" data-close>เก็บไว้</button><button class="button danger" data-confirm-dismantle="${id}">รื้อโครงสร้าง</button></div>`);return;}
if(b.dataset.confirmDismantle){closeModal();return run('dismantle',b.dataset.confirmDismantle);}
if(b.hasAttribute('data-newgame'))return newGameDialog();
if(b.dataset.difficulty){G=E.newGame(b.dataset.difficulty);tab='gather';mapSelected='clearing';save();closeModal();render();toast('การเดินทางครั้งใหม่เริ่มขึ้นแล้ว');return;}
if(b.hasAttribute('data-end-journal')){closeModal();return setTab('journal');}
 if(b.dataset.slotSave){const n=Number(b.dataset.slotSave),existing=readSlot(n);if(existing){openModal(`บันทึกทับช่อง ${n}?`,`<p>${existing.invalid?'ช่องนี้มีข้อมูลที่อ่านไม่ได้ การบันทึกทับจะลบข้อมูลเดิม':`ช่องนี้มีเซฟวันที่ ${existing.day} เวลา ${time(existing.time)} ที่${E.site(existing).name}`}</p><p>ความคืบหน้าในช่องเดิมจะถูกแทนที่ด้วยสถานะปัจจุบัน</p><div class="modal-actions"><button class="button quiet" data-close>ยกเลิก</button><button class="button primary" data-confirm-slot-save="${n}">${icon('save')}บันทึกทับ</button></div>`,'slot-confirm','SAVE SLOT');}else writeSlot(n);return;}
if(b.dataset.confirmSlotSave){const n=Number(b.dataset.confirmSlotSave);closeModal();writeSlot(n);return;}
if(b.dataset.slotLoad){const n=Number(b.dataset.slotLoad),loaded=readSlot(n);if(!loaded||loaded.invalid)return toast(loaded?.error||'ช่องนี้ยังว่าง');openModal(`โหลดช่อง ${n}?`,`<p>วันที่ ${loaded.day} เวลา ${time(loaded.time)} ที่${E.site(loaded).name}</p><p>ความคืบหน้าปัจจุบันจะถูกแทนที่</p><div class="modal-actions"><button class="button quiet" data-close>ยกเลิก</button><button class="button primary" data-confirm-slot-load="${n}">${icon('save')}โหลดเซฟนี้</button></div>`,'slot-confirm','LOAD SLOT');return;}
if(b.dataset.confirmSlotLoad){const loaded=readSlot(Number(b.dataset.confirmSlotLoad));if(!loaded||loaded.invalid)return toast(loaded?.error||'อ่านช่องบันทึกไม่ได้');G=loaded;save();closeModal();render();if(G.event)showEvent();else if(G.ended)showEnd();toast('โหลดช่องบันทึกแล้ว');return;}
if(b.hasAttribute('data-checkpoint')){try{localStorage.setItem(CHECKPOINT,JSON.stringify(G));toast('บันทึกจุดพักการเดินทางแล้ว');}catch(e){toast('บันทึกไม่สำเร็จ กรุณาส่งออกไฟล์เซฟ');}return;}
if(b.hasAttribute('data-load')){try{const raw=localStorage.getItem(CHECKPOINT);if(!raw)return toast('ยังไม่มีจุดบันทึกส่วนตัว');const loaded=E.validate(JSON.parse(raw));openModal('กลับไปยังจุดบันทึก',`<p>วันที่ ${loaded.day} เวลา ${time(loaded.time)} ที่${E.site(loaded).name} ความคืบหน้าปัจจุบันจะถูกแทนที่</p><div class="modal-actions"><button class="button quiet" data-close>ยกเลิก</button><button class="button primary" data-confirm-load>โหลดจุดบันทึก</button></div>`);}catch(e){toast('อ่านจุดบันทึกไม่ได้: '+e.message);}return;}
if(b.hasAttribute('data-confirm-load')){try{G=E.validate(JSON.parse(localStorage.getItem(CHECKPOINT)));save();closeModal();render();if(G.event)showEvent();else if(G.ended)showEnd();toast('โหลดจุดบันทึกแล้ว');}catch(e){toast(e.message);}return;}
if(b.hasAttribute('data-export')){try{if(await Platform.exportFile(`wildland-day${G.day}.json`,JSON.stringify(G,null,2)))toast('ส่งออกไฟล์เซฟแล้ว');}catch(e){toast('ส่งออกไฟล์เซฟไม่สำเร็จ');}return;}
if(b.hasAttribute('data-import')){$('importFile').click();return;}
if(b.hasAttribute('data-preview-sound')){if(!ambience.active)await ambience.toggle();else actionAudio.play('preview');if(modalMode==='settings')settings();return;}
if(b.hasAttribute('data-sound')){await ambience.toggle();if(modalMode==='settings')settings();}
});
$('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>300000)throw Error('ไฟล์ใหญ่เกิน 300 KB');const loaded=E.validate(JSON.parse(await file.text()));G=loaded;save();closeModal();render();if(G.event)showEvent();else if(G.ended)showEnd();toast('นำเข้าเซฟเรียบร้อย');}catch(err){toast('นำเข้าไม่ได้: '+err.message);}e.target.value='';});
document.addEventListener('input',e=>{
if(['transferQuantity','transferType'].includes(e.target.id)){updateTransferPreview();return;}
if(e.target.id==='effectsVolume'){
  effectsVolume=Number(e.target.value)/100;
  actionAudio.setVolume(effectsVolume);
  $('effectsVolumeValue').textContent=`${Math.round(effectsVolume*100)}%`;
  try{localStorage.setItem('wildland_effect_volume_v1',String(effectsVolume));}catch(err){}
}else if(e.target.id==='natureVolume'){
  natureVolume=Number(e.target.value)/100;
  natureAudio.setVolume(natureVolume);
  $('natureVolumeValue').textContent=`${Math.round(natureVolume*100)}%`;
  try{localStorage.setItem('wildland_nature_volume_v1',String(natureVolume));}catch(err){}
}
});
$('closeModal').innerHTML=icon('close');$('closeModal').onclick=closeModal;
$('modal').addEventListener('cancel',e=>{if(modalMode==='event')e.preventDefault();});
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('homeMark').innerHTML=icon('mountain');$('homeLink').onclick=e=>{e.preventDefault();setTab('gather');};
$('helpButton').innerHTML=icon('help');$('helpButton').onclick=showGuide;
$('settingsButton').innerHTML=icon('settings');$('settingsButton').onclick=settings;$('soundButton').onclick=()=>ambience.toggle();ambience.update();
$('sleepButton').onclick=showSleep;$('allLogs').onclick=()=>setTab('journal');
document.addEventListener('keydown',e=>{if($('modal').open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key>='1'&&e.key<=String(tabs.length))setTab(tabs[Number(e.key)-1][0]);if(e.key==='?')showGuide();});
Platform.onBack(()=>{if($('modal').open){closeModal();return true;}if(tab!=='gather'){setTab('gather');return true;}return false;});
document.addEventListener('visibilitychange',()=>{if(!ambience.context)return;if(document.hidden){actionAudio.setEnabled(false);natureAudio.setEnabled(false);ambience.context.suspend().catch(()=>{});}else if(ambience.active){ambience.context.resume().then(()=>{if(ambience.active&&!document.hidden){actionAudio.setEnabled(true);natureAudio.setEnabled(true);}}).catch(()=>{});}});
render();Landscape.init($('scene'),G);sceneReady=true;if(saveError)toast(saveError);if(G.event)showEvent();else if(G.ended)showEnd();
})();
