'use strict';
const ExpeditionUI=(()=>{
const D=WILD,E=Survival,W=WorldRules;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=id=>D.sites.find(a=>a.id===id).name;
const duration=m=>m>=60?`${Math.floor(m/60)} ชม.${m%60?` ${m%60} น.`:''}`:`${m} น.`;
function button(s,type,id,label,icon){const reason=E.available(s,type,id),[time,energy]=E.cost(s,type,id);return `<button class="button ${reason?'quiet':'primary'}" data-action="${type}" ${id?`data-id="${id}"`:''} ${reason?'disabled':''} title="${escape(reason||`${duration(time)} • พลังงาน ${energy}`)}">${icon||''}${label}</button>${reason?`<small class="world-reason">${escape(reason)}</small>`:`<small class="world-reason">${duration(time)} · พลังงาน −${energy}</small>`}`;}
function outlook(s,icon){
const active=W.active(s),next=W.hazardsFor(s,s.forecast,s.day+1),migration=W.migration(s),moving=W.migration(s,s.day+1)!==migration;
return `<section class="world-outlook"><div class="world-heading"><span>${icon('compass')} สัญญาณจากป่า</span><small>LIVING WILDERNESS</small></div><div class="world-bulletins">${s.day>=4&&s.weather==='storm'?`<div class="world-warning">${icon('storm')}<div><strong>คืนนี้พายุจะทำให้แคมป์เสียหาย</strong><p>ค้ำยันก่อนนอนลดความเสียหาย 75% • ใช้ไม้ 2 + เส้นใย 2</p></div></div>`:''}${active.map(h=>`<div class="world-warning">${icon(h.type==='flood'?'water':'wood')}<div><strong>${h.type==='flood'?'น้ำหลากที่ลำธาร':'ต้นไม้ล้มขวางทาง'}</strong><p>${name(h.edge[0])} ↔ ${name(h.edge[1])} ปิดถึงสิ้นวันที่ ${h.until}${h.type==='flood'?' • ตกปลาไม่ได้ เก็บน้ำได้ครั้งละ 1 • แคมป์ลำธารเสียหายคืนนี้':' • เปิดทางได้จากปลายทางทั้งสองด้วยขวาน'}</p></div></div>`).join('')}${next.length||(s.day>=3&&s.forecast==='storm')?`<div class="world-forecast">${icon('rain')}<div><strong>เตือนล่วงหน้า / พรุ่งนี้</strong><p>${next.map(h=>h.type==='flood'?'ลำธารจะน้ำหลาก • ทางไปเนินหินปิด':'ต้นไม้จะล้มปิดทางป่าดิบ–สถานีร้าง').join(' / ')}${s.forecast==='storm'?' • เตรียมวัสดุค้ำยันสำหรับคืนพรุ่งนี้':''}</p></div></div>`:''}<div class="migration-note">${icon('leaf')}<span>${s.day<4?'รอยสัตว์ยังอุดมสมบูรณ์ • การล่าซ้ำทำให้สัตว์ระแวง':`ฝูงสัตว์อยู่ที่${name(migration)} • รอยสัตว์ฟื้นคืนละ 2`}<small>${moving?`พรุ่งนี้ฝูงสัตว์จะย้ายไป${name(W.migration(s,s.day+1))}`:'พื้นที่อื่นฟื้น 1 ทุกสองคืน • ปลาเพิ่มคืนละ 1 หรือ 2 หลังฝน'}</small></span></div></div>${active.some(h=>h.type==='treefall'&&h.edge.includes(s.location))?`<div class="world-controls">${button(s,'clearTrail',null,'ใช้ขวานเปิดทาง',icon('axe'))}</div>`:''}</section>`;
}
function landmark(s,id,icon){
const p=D.landmarks[id],discovered=s.world.discovered.includes(id),claimed=s.world.claimed.includes(id),here=s.location===id;
return `<section class="landmark-card ${claimed?'claimed':''}"><div class="landmark-art art-${id}"><span>${icon(p.icon)}</span><small>${discovered?p.kind:'UNMARKED TERRITORY'}</small></div><div class="landmark-body"><div class="eyebrow">${claimed?'EXPEDITION COMPLETE':discovered?'DISCOVERED / จุดสำรวจพิเศษ':'A TRACE IN THE WILD / เบาะแส'}</div><h3>${discovered?p.name:'มีบางอย่างซ่อนอยู่ที่นี่'}</h3><p>${discovered?p.story:p.hint}</p>${discovered?`<div class="landmark-rewards">${Object.entries(p.reward).map(([k,n])=>`<span title="${escape(D.items[k].desc)}">${icon(D.items[k].icon)}${D.items[k].name} ×${n}</span>`).join('')}</div><p class="gear-effect">${D.items[Object.keys(p.reward)[0]].desc.split(' • ').slice(1).join(' • ')}</p>`:''}<div class="landmark-action">${claimed?`<span class="condition">${icon('check')}รับรางวัลแล้ว • ของที่เกินน้ำหนักอยู่ในคลังพื้นที่</span>`:here?discovered?button(s,'investigate',id,'เข้าสำรวจ',icon('compass')):`<span class="micro">ใช้กิจกรรม «สำรวจเส้นทาง» ด้านล่างเพื่อค้นพบจุดนี้</span>`:`<span class="micro">เดินทางมา${name(id)}เพื่อ${discovered?'เข้าสำรวจ':'ตามหาเบาะแส'}</span>`}</div></div></section>`;
}
function maintenance(s,icon){
const c=E.camp(s);if(!c.structures.length)return '';
const mats=W.repairMats(s);
return `<section class="camp-maintenance"><div class="world-heading"><span>${icon('shield')} ความแข็งแรงแคมป์</span><strong class="${c.condition<40?'danger-text':''}">${c.condition}%</strong></div><div class="meter" style="--stat:${c.condition<40?'#de8e78':'#b6c88c'}"><i style="width:${c.condition}%"></i></div><p>${c.condition<40?'เพิงพักชำรุด • กันฝนและฟื้นแรงเพิ่มไม่ได้จนกว่าจะซ่อม':'ต่ำกว่า 40% เพิงพักจะกันฝนและฟื้นแรงเพิ่มไม่ได้'}${c.braced?' • ค้ำยันคืนนี้แล้ว':''}</p><div class="maintenance-grid"><div>${button(s,'repair',null,'ซ่อม +45%',icon('tool'))}<small>${Object.entries(mats).map(([k,n])=>`${D.items[k].name} ${n}`).join(' + ')}</small></div><div>${button(s,'reinforce',null,c.braced?'ค้ำยันแล้ว':'ค้ำยันคืนนี้',icon('tent'))}<small>ไม้ฟืน 2 + เส้นใย 2 • ลดเสียหาย 75%</small></div></div></section>`;
}
function atlas(s,icon){return `<div class="atlas-heading"><strong>${icon('compass')} สมุดจุดสำรวจพิเศษ</strong><span>รับรางวัลแล้ว ${s.world.claimed.length}/7</span></div><div class="landmark-atlas">${D.sites.map(a=>`<button data-location="${a.id}" class="atlas-entry ${s.world.claimed.includes(a.id)?'claimed':''}">${icon(s.world.discovered.includes(a.id)?D.landmarks[a.id].icon:'pin')}<span><strong>${s.world.discovered.includes(a.id)?D.landmarks[a.id].name:'ยังไม่ค้นพบ'}</strong><small>${a.name}</small></span><span>${s.world.claimed.includes(a.id)?'✓':'↗'}</span></button>`).join('')}</div>`;}
return {outlook,landmark,maintenance,atlas};
})();
